config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'home/index'

  root 'home#index'

  resources :users, only: [:new, :create, :destroy]
  get 'user/document/:id' => 'users#user_by_document', as: 'user_by_document'
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :fleets
  get 'fleets/filderByCity/:id' => 'fleets#fleets_by_city', as: 'fleets_filter_by_city'

  resources :bus

  resources :packages
  get 'getPackageByTrackingID/:id' => 'packages#package_by_trackingid', as: 'getPackageByTrackingID'
  get 'getPackagesByStatus/:id' => 'packages#package_by_status', as: 'getPackageByStatus'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  def index
    @packages = Package.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_packages.html.erb
<div class="row">
    <h3 class="header center-align">Pedidos Creados</h3>
    <% @packages.each do |package| %>
        <div class="card col s3">
            <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="http://materializecss.com/images/office.jpg">
            </div>
            <div class="card-content">
                <span class="card-title activator grey-text text-darken-4">Mas Información<i class="material-icons right">more_vert</i></span>
                <p><a href="javascript:void(0);"><%= package.order_status.name %></a> - Token: <%= package.trackingid%> </p>
            </div>
            <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">Informacion del paquete:<i class="material-icons right">close</i></span>
                <p>Origen: <%=package.origin.name%></p>
                <p>Destino: <%=package.destination.name%></p>
                <p>Enviado por: <%= package.user.nil? ? ' Usuario ' : package.user.full_name%></p>
                <p>Contenido: <%= package.description %></p>
            </div>
        </div>
    <% end %>
</div>

app/views/home/index.html.erb
<br>
<h3 class="center-align">Ver Paquete</h3>
<div class="row">
    <div class="col s3"></div>
    <div class="col s6">
        <nav>
            <div class="nav-wrapper">
                <form id= "search-package">
                    <div class="input-field">
                        <input id="search" type="search" required>
                        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                        <i class="material-icons">close</i>
                    </div>
                </form>
            </div>
        </nav>
        <div id="package-info" class="row hide">
            <div class="col s3"></div>
            <div class="col s6 m6 ">
                <div class="card-panel blue">
                    <span class="white-text">
                        <h6>Estado del pedido: <span id="trackingid"></span></h6>
                        <ul>
                            <li>Direccion Actual: <span id="address"></span> </li>
                            <li>Estado: <span id="order_status"></span> </li>
                            <li>Camion Asignado: <span id="bus"></span> </li>
                            <input type="hidden" name="package-id"  id="package-id">
                        </ul>
                        <div class="center-align cancel-package-button">
                            <a class="waves-effect waves-light btn" href="javascript:void(0);">Cancelar</a>
                        </div>
                    </span>
                </div>
            </div>
        </div>

    </div>
</div>
<%= render  "packages" %>
<div class="fixed-action-btn">
    <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_package_path, class: "btn-floating btn-large red pulse" %>
</div>