config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'home/index'

  root 'home#index'

  resources :users, only: [:new, :create, :destroy]
  get 'user/document/:id' => 'users#user_by_document', as: 'user_by_document'
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :fleets
  get 'fleets/filderByCity/:id' => 'fleets#fleets_by_city', as: 'fleets_filter_by_city'

  resources :bus

  resources :packages
  get 'getPackageByTrackingID/:id' => 'packages#package_by_trackingid', as: 'getPackageByTrackingID'
  get 'getPackagesByStatus/:id' => 'packages#package_by_status', as: 'getPackageByStatus'
end

app/views/layouts/_menu.html.erb
<nav>
  <div class="nav-wrapper">
    <%=link_to 'APP', root_path, class: 'brand-logo'%>
    <ul id="nav-mobile" class="right ">
     <% if current_user %>
      <li><%= link_to 'Panel', admin_index_path, class: 'nav-link' %></li>
      <li><%= link_to 'Log Out', log_out_path, method: :delete, class: 'nav-link' %></li>
     <%else%>
      <li><%= link_to 'Sign Up', sign_up_path, class: 'nav-link' %></li>
      <li><%= link_to 'Log In', log_in_path, class: 'nav-link' %></li>
     <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShipmentsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBRxC6Y4f-j6nECyHWigtBATtJyXyha-XU&callback=initMap"
                                       async defer></script>-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyBRxC6Y4f-j6nECyHWigtBATtJyXyha-XU"></script>
  </head>

  <body>
    <%= render 'layouts/menu'%>
    <div class="container-fluid">
      <%= yield %>      
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
  </body>
</html>